import Head from 'next/head';
import { useInView } from 'react-intersection-observer';

import Footer from '../footer';
import Sidebar from '../sidebar';

const backgrounds = {
  purpleGradient: 'bg-gradient-to-b from-purple-dark via-black to-gray-500',
  gray: 'bg-gray-500',
};

const MainLayout = ({
  pageTitle,
  pageBackground,
  children,
}: MainLayoutProps) => {
  return (
    <div>
      <Head>
        <title>{pageTitle}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='author' content='Kayle San Juan' />
        <meta name='twitter:site' content='@sjkayle' />
        <meta name='twitter:creator' content='@sjkayle' />
        <meta name='twitter:image' content='/assets/hero.png' />
        <meta property='og:site_name' content="Kayle San Juan's Portfolio" />
        <meta property='og:type' content='website' />
        <meta property='og:image' content='/assets/hero.png' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Sidebar />
      <main
        className={`${backgrounds[pageBackground]} md:pl-60 pb-24 min-h-screen`}
      >
        {children}
      </main>
      <Footer />
    </div>
  );
};

type MainLayoutProps = {
  children: JSX.Element[];
  pageTitle: string;
  pageBackground: 'purpleGradient' | 'gray';
};

export default MainLayout;
